version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      POSTGRES_DB: ${DB_NAME:?}
    volumes:
      - ./data:/var/lib/postgresql/data

  cidrlistings:
    image: ghcr.io/aorith/cidr-listings:latest
    container_name: cidrlistings
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env
    user: "1000"
    depends_on:
      - postgres

  worker1:
    image: ghcr.io/aorith/cidr-listings:latest
    entrypoint: python3
    command: -m app.worker
    env_file:
      - ./.env
    user: "1000"
    depends_on:
      - postgres
      - cidrlistings

